# Use this file as your netlify.toml file
# client side route redirects are auto
# generated.
[[redirects]]
  from = "/en/development-environments/native-tokens/native-tokens/"
  to = "https://docs.cardano.org/en/latest/native-tokens/getting-started-with-native-tokens.html"
  status = 301

[build]
  functions = "functions"
[[redirects]]
  from = "/api/*"
  to="/.netlify/functions/:splat"
  status=200